---
title: "Projetos"
description: |
  O objetivo é a apresentação de como as técnicas de machine learning podem ser empregadas para a elaboração de trabalhos acadêmicos e análises. Os projetos listados serão executados com bases de dados públicos, temas variados e sem fins lucrativos, dedicando-se na demonstração para a comunidade interessada na elaboração e divulgação científica.

listing:
  - id: ehr
    max-description-length: 500
    image-height: 150px
    fields: [title, description,categories]
    contents:
      - project_1
      - project_2
    type: grid
    grid-item-border: true
    grid-columns: 2

toc: false
title-block-style: plain
  # - id: packages
  #   max-description-length: 80
  #   image-height: 250px
  #   fields: [title, description]
  #   contents:
  #     - pkg_1
  #     - pkg_2
  #   type: table
  #   grid-item-border: false
  #   sort-ui: false
  #   filter-ui: false
sidebar: false
---

::: {#ehr}
:::

## Artigos completos publicados em periódicos

CATEIA, JULIO VICENTE; SAVARD, LUC; ALMEIDA, EDIVO OLIVEIRA DE; **BARBOSA, W.** Informality, Trade Facilitation, and Trade Flows: Evidence from Guinea-Bissau. INTERNATIONAL JOURNAL OF ECONOMICS AND FINANCE. , v.14, p.21, 2022.

CATEIA, J. V.; OLIVEIRA, E. A.; **BARBOSA, W.** ESTIMAÇÃO DO COMÉRCIO INTERNACIONAL BRASILEIRO EM CLUSTERS. Análise Econômica (UFRGS) on line. , v.39, p.133 - 160, 2021. Referências adicionais: Português.

**BARBOSA, W.**; OLIVEIRA, E. A.; CATEIA, J. V. Farming and Deforestation in MATOPIBA Municipalities: A Spatial Analysis. JOURNAL OF INTERNATIONAL AND GLOBAL ECONOMIC STUDIES., v.14, p.1-14 - , 2021.

OLIVEIRA, E. A.; FEISTEL, P. R.; **BARBOSA, W.** O Pecado Original Doméstico: Uma Análise Da Experiência Brasileira Entre 2001 A 2016. ESTUDO &amp; DEBATE (ONLINE)., v.26, p.7 - 33, 2019.

OLIVEIRA, E. A.; **BARBOSA, W.** ; CATEIA, J. V.; FEISTEL, P. R. AS EXPORTAÇÕES BRASILEIRAS POR GRAU DE ELABORAÇÃO ENTRE 1980 E 2015: APLICAÇÃO DO MODELO EATON-KORTUM À LUZ DA TEORIA CEPALINA. Análise Econômica (UFRGS) on-line. , v.36, p.179 - 201, 2018.

SILVA, J. V. S.; **BARBOSA, W.** ; FREITAS, C. A. Complementaridade Comercial entre Brasil e América do Sul: Aplicação do modelo gravitacional em dados em painel para o mercado de bens de alta intensidade tecnológica. RBEE. REVISTA BRASILEIRA DE ECONOMIA DE EMPRESAS. , v.18, p.43 - 63, 2018.

SILVA, J. V. S.; **BARBOSA, W.** A América do Sul no Dinamismo Comercial Brasileiro: Um Estudo Das Complementaridades Por Intensidade Tecnológica. OBSERVATORIO DE LA ECONOMÍA LATINOAMERICANA. , v.3, p.1-17 - , 2017.

**BARBOSA, W.** ; OLIVEIRA, E. A.; FREITAS, C. A.; SILVA, J. V. S. UMA ANÁLISE DA CURVA DE KUZNETS PARA OS MUNICÍPIOS BRASILEIROS (1991, 2000, 2010). ECONOMIA &amp; REGIÃO. , v.5, p.65 - 83, 2017.

OLIVEIRA, E. A.; **BARBOSA, W.** ; ROHENKOHL, J. E. CRISE SUBPRIME: UMA EXPLICAÇÃO COM BASE NO CONCEITO DE DIREITOS DE PROPRIEDADE. Revista da FAE. , v.19, p.52 - 74, 2016.

**BARBOSA, W.** ; OLIVEIRA, E. A.; FREITAS, C. A.; FEISTEL, P. R. MIGRAÇÕES INTERESTADUAIS: UMA APLICAÇÃO DO MODELO GRAVITACIONAL PARA OS ESTADOS BRASILEIROS. Revista Brasileira de Estudos Regionais e Urbanos. , v.10, p.156 - 176, 2016.

OLIVEIRA, E. A.; **BARBOSA, W.** ; FREITAS, C. A. Ordem e caos: um conceito alternativo de mercado. Estudos do CEPE. , p.04 - , 2016.

**BARBOSA, W.** ; PELINSKI, A. R.; CARMO, A. S. S. Existe desindustrialização no Estado do Paraná? um teste empírico para o período de 1996 a 2012. INFORME GEPEC (ONLINE). , v.19, p.55 - 79, 2015.


<!-- ## Eventos

## Revisão de períodicos -->




