project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "William Barbosa"


  page-footer:
    left: "&copy; Copyright 2023, William Barbosa"
    right: "Essa página foi construída com [Quarto](https://quarto.org/)."

  navbar:
      right: #left:
      # - text: "Início"
      #   file: index.qmd
      - text: "Posts"
        href: blog.qmd

      - text: "Projetos"
        href: projects/index.qmd


      - text: "Resumo"
        href: Curriculo/William_Barbosa.pdf

      - text: "Indicações"
        menu:
        - text: "Use R!"
          href: 'https://cran.r-project.org/'
        - text: "Anaconda"
          href: 'https://docs.anaconda.com/free/anaconda/install/index.html'
        - text: "Julia"
          href: 'https://julialang.org/downloads/'
        - text: 'QGIS'
          href: 'https://www.qgis.org/pt_BR/site/forusers/download.html'


  sidebar:
    pinned: true
    align: center
    style: "floating"
    # background: primary
    collapse-level: 2
    contents:
      # - text: "Projetos"
      #   href: projects/index.qmd
      # - text: "Pensar em algo com o que a comunidade stá falando"
      #   href: talks/index.qmd
      - section: "About"
        contents:
          - text: "About me"
            href: about.qmd
      - section: "Publicações"
        contents:
        - text: "Revistas"

format:
  html:
    theme: custom.scss #william-tema.scss
    css: styles.css
    toc: true
    # grid:
      #  sidebar-width: 200px
    #   body-width: 900px
    #   margin-width: 400px
      # gutter-width: 20px

# template-partials:
  # - noto.html
  # - title-block.html

# include-in-header: title-block.html

